In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import du fichier CSV Fusion_FR_Mapping.csv

data_join_FR = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Fusion_FR_Mapping.csv',decimal=".")

data_join_FR.head()

,Unnamed: 0,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No)
0,0,Kosovo,XKX,983.0,-1,NaN,NaN,NaN,NaN,NaN
1,1,Armenia,ARM,51.0,1,54.0,235.0,35.000000,-3.84,339.74
2,2,Afghanistan,AFG,4.0,2,5.0,254.0,-103.185185,78.88,1185.84
3,3,Albania,ALB,8.0,3,85.0,438.0,38.000000,-7.88,421.64
4,4,Algeria,DZA,12.0,4,22.0,4858.0,2.000000,36.04,NaN

In [ ]:
#import du fichier CSV france_dist_eco.csv

france_dist_eco = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/france_dist_eco.csv',decimal=".")

france_dist_eco.head()

  Country Code  Distance_Economique Pays_France(Km)
0          ABW                             7711.830
1          AFG                             5489.888
2          AGO                             6363.600
3          AIA                             6737.844
4          ALB                             1461.321

In [ ]:
# jointure des 2 dataframes sur 1 colonnes Country Code

Mapping_Distance = data_join_FR.merge(france_dist_eco, on=["Country Code"], how='outer')
display(Mapping_Distance)

,Unnamed: 0,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km)
0,21.0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830
1,2.0,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888
2,7.0,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600
3,227.0,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844
4,3.0,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321
...,...,...,...,...,...,...,...,...,...,...,...
245,NaN,NaN,YUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1397.047
246,183.0,South Africa,ZAF,710.0,202.0,143.0,5357.0,451.000000,28.52,931.43,8750.608
247,NaN,NaN,ZAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5995.903
248,224.0,Zambia,ZMB,894.0,251.0,11.0,551.0,11.000000,66.59,3653.36,7221.197
249,162.0,Zimbabwe,ZWE,716.0,181.0,16.0,44.0,-126.185185,21.52,3041.81,7759.680

In [ ]:
#Suppression de la colonne Unnamed: 0
Mapping_Distance = Mapping_Distance.drop('Unnamed: 0', axis=1)
Mapping_Distance.head()

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km)
0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830
1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888
2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600
3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844
4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321

In [ ]:
#vérification des valeurs manquantes
print(Mapping_Distance.isnull().sum())

Zone                                                      9
Country Code                                              0
Numeric                                                   9
Code zone                                                 9
Disponibilité alimentaire (Kcal/personne/jour)           78
Quantité Aliments_disponible Poules(Milliers tonnes)     76
Export_Utile(Milliers tonnes)                            78
Taux de croissance_population [%]                        14
Emploi dans la production_vegetale_animale (1000No)     108
Distance_Economique Pays_France(Km)                      24
dtype: int64

In [ ]:
#Détail des valeurs manquantes pour la variable Zone
Mapping_Distance.loc[Mapping_Distance['Zone'].isnull(),:]

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km)
37,NaN,CCK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11388.360
54,NaN,CXR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11866.100
158,NaN,NFK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17659.580
170,NaN,PAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3168.216
172,NaN,PCN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15152.120
186,NaN,ROM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1723.568
220,NaN,TMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13172.920
245,NaN,YUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1397.047
247,NaN,ZAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5995.903

In [ ]:
Mapping_Distance.loc[37,'Zone']= 'Cocos Islands'
Mapping_Distance.loc[37,'Numeric']= 166
Mapping_Distance.loc[54,'Zone']= 'Christmas Island'
Mapping_Distance.loc[54,'Numeric']= 162
Mapping_Distance.loc[158,'Zone']= 'Norfolk Island'
Mapping_Distance.loc[158,'Numeric']= 574
Mapping_Distance.loc[172,'Zone']= 'Pitcairn'
Mapping_Distance.loc[172,'Numeric']= 612

In [ ]:
Mapping_Distance.loc[182,'Distance_Economique Pays_France(Km)']= 3168.216

In [ ]:
print(Mapping_Distance.loc[Mapping_Distance['Country Code']== 'PSE'])

          Zone Country Code  Numeric  Code zone  \
182  Palestine          PSE    275.0      299.0

     Disponibilité alimentaire (Kcal/personne/jour)  \
182                                             NaN

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
182                                                NaN

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
182                            NaN                              50.84

     Emploi dans la production_vegetale_animale (1000No)  \
182                                              46.46

     Distance_Economique Pays_France(Km)
182                             3168.216

In [ ]:
print(Mapping_Distance.loc[Mapping_Distance['Country Code']== 'ZAF'])
#Country code ZAR : pas trouvé

             Zone Country Code  Numeric  Code zone  \
246  South Africa          ZAF    710.0      202.0

     Disponibilité alimentaire (Kcal/personne/jour)  \
246                                           143.0

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
246                                             5357.0

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
246                          451.0                              28.52

     Emploi dans la production_vegetale_animale (1000No)  \
246                                             931.43

     Distance_Economique Pays_France(Km)
246                             8750.608

In [ ]:
print(Mapping_Distance.loc[Mapping_Distance['Country Code']== 'ROU'])

        Zone Country Code  Numeric  Code zone  \
187  Romania          ROU    642.0      183.0

     Disponibilité alimentaire (Kcal/personne/jour)  \
187                                            66.0

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
187                                             7718.0

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
187                           77.0                             -11.89

     Emploi dans la production_vegetale_animale (1000No)  \
187                                             867.68

     Distance_Economique Pays_France(Km)
187                                  NaN

In [ ]:
Mapping_Distance.loc[187,'Distance_Economique Pays_France(Km)']= 1723.568

In [ ]:
print(Mapping_Distance.loc[Mapping_Distance['Country Code']== 'TLS'])

            Zone Country Code  Numeric  Code zone  \
219  Timor-Leste          TLS    626.0      176.0

     Disponibilité alimentaire (Kcal/personne/jour)  \
219                                            14.0

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
219                                                6.0

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
219                    -121.185185                              43.38

     Emploi dans la production_vegetale_animale (1000No)  \
219                                             168.23

     Distance_Economique Pays_France(Km)
219                                  NaN

In [ ]:
Mapping_Distance.loc[219,'Distance_Economique Pays_France(Km)']= 13172.920

In [ ]:
print(Mapping_Distance.loc[Mapping_Distance['Country Code']== 'SRB'])

       Zone Country Code  Numeric  Code zone  \
201  Serbia          SRB    688.0      272.0

     Disponibilité alimentaire (Kcal/personne/jour)  \
201                                            35.0

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
201                                             2833.0

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
201                            5.0                              -3.75

     Emploi dans la production_vegetale_animale (1000No)  \
201                                             433.37

     Distance_Economique Pays_France(Km)
201                                  NaN

In [ ]:
print(Mapping_Distance.loc[Mapping_Distance['Country Code']== 'XKX'])

       Zone Country Code  Numeric  Code zone  \
243  Kosovo          XKX    983.0       -1.0

     Disponibilité alimentaire (Kcal/personne/jour)  \
243                                             NaN

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
243                                                NaN

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
243                            NaN                                NaN

     Emploi dans la production_vegetale_animale (1000No)  \
243                                                NaN

     Distance_Economique Pays_France(Km)
243                                  NaN

In [ ]:
print(Mapping_Distance.loc[Mapping_Distance['Country Code']== 'MNE'])

           Zone Country Code  Numeric  Code zone  \
144  Montenegro          MNE    499.0      273.0

     Disponibilité alimentaire (Kcal/personne/jour)  \
144                                            55.0

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
144                                               41.0

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
144                            8.0                               1.61

     Emploi dans la production_vegetale_animale (1000No)  \
144                                                NaN

     Distance_Economique Pays_France(Km)
144                                  NaN

In [ ]:
#La yogosslavie n'existe plus aujourd'hui: parmis les pays qui la composaient et qui n'ont pas de Distance_Economique Pays_France(Km)
# et qui ont assez de données qu'on peut explorer on trouve la Serbie et Montenegro : Nous mettrons à jour la valeur de Distance_Economique Pays_France(Km)
Mapping_Distance.loc[201,'Distance_Economique Pays_France(Km)']= 1397.047
Mapping_Distance.loc[144,'Distance_Economique Pays_France(Km)']= 1397.047

In [ ]:
#Détail des valeurs manquantes pour la variable Zone
Mapping_Distance.loc[Mapping_Distance['Zone'].isnull(),:]

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km)
170,NaN,PAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3168.216
186,NaN,ROM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1723.568
220,NaN,TMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13172.920
245,NaN,YUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1397.047
247,NaN,ZAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5995.903

In [ ]:
# Mise à jour effectué au niveau des Zone --> Suppression des lignes
Mapping_Distance = Mapping_Distance[Mapping_Distance['Zone'].notna()]

In [ ]:
#vérification des valeurs manquantes
print(Mapping_Distance.isnull().sum())

Zone                                                      0
Country Code                                              0
Numeric                                                   0
Code zone                                                 4
Disponibilité alimentaire (Kcal/personne/jour)           73
Quantité Aliments_disponible Poules(Milliers tonnes)     71
Export_Utile(Milliers tonnes)                            73
Taux de croissance_population [%]                         9
Emploi dans la production_vegetale_animale (1000No)     103
Distance_Economique Pays_France(Km)                      19
dtype: int64

In [ ]:
#Détail des valeurs manquantes pour la variable Code Zone
Mapping_Distance.loc[Mapping_Distance['Code zone'].isnull(),:]

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km)
37,Cocos Islands,CCK,166.0,NaN,NaN,NaN,NaN,NaN,NaN,11388.36
54,Christmas Island,CXR,162.0,NaN,NaN,NaN,NaN,NaN,NaN,11866.10
158,Norfolk Island,NFK,574.0,NaN,NaN,NaN,NaN,NaN,NaN,17659.58
172,Pitcairn,PCN,612.0,NaN,NaN,NaN,NaN,NaN,NaN,15152.12

In [ ]:
Mapping_Distance.head()

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km)
0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830
1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888
2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600
3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844
4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321

In [ ]:
#préparation de l'export du dataframe en fichier CSV

Mapping_Distance.to_csv('/content/drive/MyDrive/Colab Notebooks/Mapping_Distance.csv', index=True)