In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import du fichier CSV Fusion_Donnee_Alimentaire_Population.csv

data_C = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Fusion_Donnee_Alimentaire_Population.csv',decimal=".", index_col=0)
data_C.head()

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%]
Code zone,,,,,
1,Arménie,54.0,235.0,35.000000,-3.84
2,Afghanistan,5.0,254.0,-103.185185,78.88
3,Albanie,85.0,438.0,38.000000,-7.88
4,Algérie,22.0,4858.0,2.000000,36.04
5,Samoa américaines,NaN,NaN,NaN,-4.07

In [ ]:
data_C.shape

(238, 5)

In [ ]:
#import du fichier CSV Emlpoi_prod_animale

prod_animale = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Emlpoi_prod_animale.csv',decimal=".", index_col=0)
prod_animale.head()

                  Zone  Emploi dans la production_vegetale_animale (1000No)
Code zone
1              Arménie                                             339.74
2          Afghanistan                                            1185.84
3              Albanie                                             421.64
7               Angola                                            5998.46
9            Argentine                                              68.22

In [ ]:
prod_animale.shape

(142, 2)

In [ ]:
# jointure des dataframes data_dispo_calorie + df_alimentation_animeaux + data_export_import + poplation_taux_croissance
# + Emploi dans la production_vegetale_animale

data_D = data_C.merge(prod_animale, on=["Code zone","Zone"], how='outer')
display(data_D)

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No)
Code zone,,,,,,
1,Arménie,54.0,235.0,35.000000,-3.84,339.74
2,Afghanistan,5.0,254.0,-103.185185,78.88,1185.84
3,Albanie,85.0,438.0,38.000000,-7.88,421.64
4,Algérie,22.0,4858.0,2.000000,36.04,NaN
5,Samoa américaines,NaN,NaN,NaN,-4.07,NaN
...,...,...,...,...,...,...
279,Curaçao,NaN,NaN,NaN,6.85,NaN
280,Sint Maarten (partie néerlandaise),NaN,NaN,NaN,19.63,NaN
281,Saint-Martin (partie française),NaN,NaN,NaN,-0.49,NaN
282,Saint-Barthélemy,NaN,NaN,NaN,5.06,NaN
299,Palestine,NaN,NaN,NaN,50.84,46.46

In [ ]:
#préparation de l'export du dataframe en fichier CSV

data_D.to_csv('/content/drive/MyDrive/Colab Notebooks/Fusion_Emploi_Alim_Population.csv', index=True)