In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import du fichier CSV Fusion_Emploi_Alim_Population.csv

data_D = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Fusion_Emploi_Alim_Population.csv',decimal=".")

data_D.head()

,Code zone,Zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No)
0,1,Arménie,54.0,235.0,35.000000,-3.84,339.74
1,2,Afghanistan,5.0,254.0,-103.185185,78.88,1185.84
2,3,Albanie,85.0,438.0,38.000000,-7.88,421.64
3,4,Algérie,22.0,4858.0,2.000000,36.04,NaN
4,5,Samoa américaines,NaN,NaN,NaN,-4.07,NaN

In [ ]:
#Verification de type des variables
data_D.dtypes

Code zone                                                 int64
Zone                                                     object
Disponibilité alimentaire (Kcal/personne/jour)          float64
Quantité Aliments_disponible Poules(Milliers tonnes)    float64
Export_Utile(Milliers tonnes)                           float64
Taux de croissance_population [%]                       float64
Emploi dans la production_vegetale_animale (1000No)     float64
dtype: object

In [ ]:
#Lecture du fichier Final_mapping_pays.csv

mapping_pays= pd.read_csv('/content/drive/MyDrive/Colab_Projet_Poule/Final_mapping_pays.csv')
mapping_pays.head()

             Zone Country Code  Numeric  Code zone
0     Afghanistan          AFG      4.0          2
1         Albania          ALB      8.0          3
2         Algeria          DZA     12.0          4
3  American Samoa          ASM     16.0          5
4         Andorra          AND     20.0          6

In [ ]:
#Verification de type des variables
mapping_pays.dtypes

Zone             object
Country Code     object
Numeric         float64
Code zone         int64
dtype: object

In [ ]:
# jointure des 2 dataframes sur 1 colonnes Code zone

data_join_FR = mapping_pays.merge(data_D, on=["Code zone"], how='outer')
display(data_join_FR)

,Zone_x,Country Code,Numeric,Code zone,Zone_y,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No)
0,Kosovo,XKX,983.0,-1,NaN,NaN,NaN,NaN,NaN,NaN
1,Armenia,ARM,51.0,1,Arménie,54.0,235.0,35.000000,-3.84,339.74
2,Afghanistan,AFG,4.0,2,Afghanistan,5.0,254.0,-103.185185,78.88,1185.84
3,Albania,ALB,8.0,3,Albanie,85.0,438.0,38.000000,-7.88,421.64
4,Algeria,DZA,12.0,4,Algérie,22.0,4858.0,2.000000,36.04,NaN
...,...,...,...,...,...,...,...,...,...,...
238,St.Martin(Frensh part),MAF,663.0,281,Saint-Martin (partie française),NaN,NaN,NaN,-0.49,NaN
239,Saint-Barthélemy,BLM,652.0,282,Saint-Barthélemy,NaN,NaN,NaN,5.06,NaN
240,Jersey,JEY,832.0,283,NaN,NaN,NaN,NaN,NaN,NaN
241,Palestine,PSE,275.0,299,Palestine,NaN,NaN,NaN,50.84,46.46
242,Chine,CN,159.0,351,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#vérification des valeurs manquantes
print(data_join_FR.isnull().sum())

Zone_x                                                    2
Country Code                                              2
Numeric                                                   2
Code zone                                                 0
Zone_y                                                    3
Disponibilité alimentaire (Kcal/personne/jour)           71
Quantité Aliments_disponible Poules(Milliers tonnes)     69
Export_Utile(Milliers tonnes)                            71
Taux de croissance_population [%]                         5
Emploi dans la production_vegetale_animale (1000No)     101
dtype: int64

In [ ]:
#Détail des valeurs manquantes pour la variable Zone_x
data_join_FR.loc[data_join_FR['Zone_x'].isnull(),:]

,Zone_x,Country Code,Numeric,Code zone,Zone_y,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No)
167,NaN,NaN,NaN,186,Serbie-et-Monténégro,NaN,NaN,NaN,-2.88,NaN
186,NaN,NaN,NaN,206,Soudan (ex),NaN,NaN,NaN,34.97,NaN

In [ ]:
print(data_join_FR.loc[data_join_FR['Zone_x']== 'Sudan'])

    Zone_x Country Code  Numeric  Code zone  Zone_y  \
233  Sudan          SDN    729.0        276  Soudan

     Disponibilité alimentaire (Kcal/personne/jour)  \
233                                             5.0

     Quantité Aliments_disponible Poules(Milliers tonnes)  \
233                                              713.0

     Export_Utile(Milliers tonnes)  Taux de croissance_population [%]  \
233                    -130.185185                              15.49

     Emploi dans la production_vegetale_animale (1000No)
233                                             3100.3

In [ ]:
# Serbie-et-Monténégro et Soudan(ex) n'existe plus --> Suppression des lignes
data_join_FR = data_join_FR[data_join_FR['Zone_x'].notna()]

In [ ]:
#Détail des valeurs manquantes pour la variable Zone_y
data_join_FR.loc[data_join_FR['Zone_y'].isnull(),:]

,Zone_x,Country Code,Numeric,Code zone,Zone_y,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No)
0,Kosovo,XKX,983.0,-1,NaN,NaN,NaN,NaN,NaN,NaN
240,Jersey,JEY,832.0,283,NaN,NaN,NaN,NaN,NaN,NaN
242,Chine,CN,159.0,351,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Suppression de la colonne Zone_y
data_join_FR = data_join_FR.drop('Zone_y', axis=1)

In [ ]:
# Renommage des colonnes de Zone_x
data_join_FR = data_join_FR.rename(columns={'Zone_x': 'Zone'})
data_join_FR.head()
#Kosovo n'a pas un code zone ISO attribué

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No)
0,Kosovo,XKX,983.0,-1,NaN,NaN,NaN,NaN,NaN
1,Armenia,ARM,51.0,1,54.0,235.0,35.000000,-3.84,339.74
2,Afghanistan,AFG,4.0,2,5.0,254.0,-103.185185,78.88,1185.84
3,Albania,ALB,8.0,3,85.0,438.0,38.000000,-7.88,421.64
4,Algeria,DZA,12.0,4,22.0,4858.0,2.000000,36.04,NaN

In [ ]:
#vérification des valeurs manquantes
print(data_join_FR.isnull().sum())

Zone                                                     0
Country Code                                             0
Numeric                                                  0
Code zone                                                0
Disponibilité alimentaire (Kcal/personne/jour)          69
Quantité Aliments_disponible Poules(Milliers tonnes)    67
Export_Utile(Milliers tonnes)                           69
Taux de croissance_population [%]                        5
Emploi dans la production_vegetale_animale (1000No)     99
dtype: int64

In [ ]:
#préparation de l'export du dataframe en fichier CSV

data_join_FR.to_csv('/content/drive/MyDrive/Colab Notebooks/Fusion_FR_Mapping.csv', index=True)