In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import du datafrme data_export_import

data_export_import = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_export_import.csv',decimal=".", index_col=0)
data_export_import.head()

                  Zone  Export_Utile(Milliers tonnes)
Code zone
1              Arménie                      35.000000
2          Afghanistan                    -103.185185
3              Albanie                      38.000000
4              Algérie                       2.000000
7               Angola                     277.000000

In [ ]:
#import du datafrme data_dispo_calorie

data_dispo_calorie = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_dispo_calorie.csv',decimal=".", index_col=0)
data_dispo_calorie.head()

                  Zone  Disponibilité alimentaire (Kcal/personne/jour)
Code zone
1              Arménie                                            54.0
2          Afghanistan                                             5.0
3              Albanie                                            85.0
4              Algérie                                            22.0
7               Angola                                            35.0

In [ ]:
#import du datafrme df_alimentation_animeaux

df_alimentation_animeaux = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/df_alimentation_animeaux.csv',decimal=".", index_col=0)
df_alimentation_animeaux.head()

                  Zone  Quantité Aliments_disponible Poules(Milliers tonnes)
Code zone
1              Arménie                                              235.0
2          Afghanistan                                              254.0
3              Albanie                                              438.0
4              Algérie                                             4858.0
7               Angola                                             5873.0

In [ ]:
# jointure des dataframes data_dispo_calorie et df_alimentation_animeaux

data_A = data_dispo_calorie.merge(df_alimentation_animeaux, on=["Code zone","Zone"], how='outer')
display(data_A)

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes)
Code zone,,,
1,Arménie,54.0,235.0
2,Afghanistan,5.0,254.0
3,Albanie,85.0,438.0
4,Algérie,22.0,4858.0
7,Angola,35.0,5873.0
...,...,...,...
255,Belgique,44.0,2863.0
256,Luxembourg,69.0,108.0
272,Serbie,35.0,2833.0
273,Monténégro,55.0,41.0
276,Soudan,5.0,713.0

In [ ]:
# jointure des dataframes data_dispo_calorie + df_alimentation_animeaux + data_export_import

data_B = data_A.merge(data_export_import, on=["Code zone","Zone"], how='outer')
data_B.reset_index(inplace=True)
display(data_B)

,Code zone,Zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes)
0,1,Arménie,54.0,235.0,35.000000
1,2,Afghanistan,5.0,254.0,-103.185185
2,3,Albanie,85.0,438.0,38.000000
3,4,Algérie,22.0,4858.0,2.000000
4,7,Angola,35.0,5873.0,277.000000
...,...,...,...,...,...
169,255,Belgique,44.0,2863.0,-318.000000
170,256,Luxembourg,69.0,108.0,10.000000
171,272,Serbie,35.0,2833.0,5.000000
172,273,Monténégro,55.0,41.0,8.000000
173,276,Soudan,5.0,713.0,-130.185185

In [ ]:
#import du datafrme poplation_taux_croissance

poplation_taux_croissance = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/poplation_taux_croissance.csv',decimal=".", index_col=0)
poplation_taux_croissance.head()

                        Zone  taux_croissance
Code zone
1                    Arménie            -3.84
2                Afghanistan            78.88
3                    Albanie            -7.88
4                    Algérie            36.04
5          Samoa américaines            -4.07

In [ ]:
# jointure des dataframes data_dispo_calorie + df_alimentation_animeaux + data_export_import + poplation_taux_croissance

data_C = data_B.merge(poplation_taux_croissance, on=["Code zone","Zone"], how='outer')
display(data_C)

,Code zone,Zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),taux_croissance
0,1,Arménie,54.0,235.0,35.000000,-3.84
1,2,Afghanistan,5.0,254.0,-103.185185,78.88
2,3,Albanie,85.0,438.0,38.000000,-7.88
3,4,Algérie,22.0,4858.0,2.000000,36.04
4,5,Samoa américaines,NaN,NaN,NaN,-4.07
...,...,...,...,...,...,...
233,279,Curaçao,NaN,NaN,NaN,6.85
234,280,Sint Maarten (partie néerlandaise),NaN,NaN,NaN,19.63
235,281,Saint-Martin (partie française),NaN,NaN,NaN,-0.49
236,282,Saint-Barthélemy,NaN,NaN,NaN,5.06
237,299,Palestine,NaN,NaN,NaN,50.84

In [ ]:
#Renommage de la  colonne taux_croissance
data_C = data_C.rename(columns={'taux_croissance':'Taux de croissance_population [%]'})

In [ ]:
#préparation de l'export du dataframe en fichier CSV

data_C.to_csv('/content/drive/MyDrive/Colab Notebooks/Fusion_Donnee_Alimentaire_Population.csv', index=False)

In [ ]:
data_C.head()

,Code zone,Zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%]
0,1,Arménie,54.0,235.0,35.000000,-3.84
1,2,Afghanistan,5.0,254.0,-103.185185,78.88
2,3,Albanie,85.0,438.0,38.000000,-7.88
3,4,Algérie,22.0,4858.0,2.000000,36.04
4,5,Samoa américaines,NaN,NaN,NaN,-4.07