In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#lecture du fichier terre agricole bio téléchargé du site Fibl : Ils publient chaque année
#des statistiques sur la surface agricole gérée en bio dans chaque pays — c’est-à-dire le nombre d’hectares certifiés bio.

df_terre_agricole = pd.read_csv('/content/drive/MyDrive/Colab_Projet_Poule/Terre_agricole_bio.csv')
df_terre_agricole.shape

(159, 2)

In [4]:
df_terre_agricole.head()

     Country  Organic area share of total farmland [%]
0    Albania                                      0.06
1    Algeria                                      0.01
2    Andorra                                      0.01
3  Argentina                                      3.43
4    Armenia                                      0.03

In [5]:
#Verification de type des variables
df_terre_agricole.dtypes

Country                                      object
Organic area share of total farmland [%]    float64
dtype: object

In [6]:
#vérification des valeurs manquantes
print(df_terre_agricole.isnull().sum())

Country                                     0
Organic area share of total farmland [%]    0
dtype: int64

In [7]:
# Renommage de la colonne country en Zone
df_terre_agricole = df_terre_agricole.rename(columns={'Country': 'Zone'})
df_terre_agricole

,Zone,Organic area share of total farmland [%]
0,Albania,0.06
1,Algeria,0.01
2,Andorra,0.01
3,Argentina,3.43
4,Armenia,0.03
...,...,...
154,Vanuatu,3.44
155,Venezuela (Bolivarian Republic of),0.01
156,Viet Nam,1.41
157,Zambia,0.01
158,Zimbabwe,0.00

In [8]:
df_terre_agricole = df_terre_agricole.rename(columns={'Organic area share of total farmland [%]': '[%]surfaces agricoles biologiques/total des terres agricoles'})

In [9]:
#Verification s'il y a des outliers
df_terre_agricole.describe()

       [%]surfaces agricoles biologiques/total des terres agricoles
count                                         159.000000
mean                                            3.822956
std                                             6.644402
min                                             0.000000
25%                                             0.130000
50%                                             0.790000
75%                                             3.735000
max                                            44.580000

In [10]:
#Vérification des Doublons
df_terre_agricole.loc[df_terre_agricole[['Zone', '[%]surfaces agricoles biologiques/total des terres agricoles']].duplicated(keep=False),:]

Empty DataFrame
Columns: [Zone, [%]surfaces agricoles biologiques/total des terres agricoles]
Index: []

In [11]:
#préparation de l'export du dataframe en fichier CSV

df_terre_agricole.to_csv('/content/drive/MyDrive/Colab Notebooks/Terre_agricole_bio.csv', index=False)